encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("wiki/<str:title>", views.wiki, name="get"),
    path("random", views.random, name="random"),
    path("search", views.search, name="search"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from . import util
import random as rn
import markdown2


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def add(request):
    if request.method == "POST":
        form = util.AddWikiForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            # check that there is no other record with the same name
            if title not in util.list_entries():
                util.save_entry(title, form.cleaned_data['content'])
                return HttpResponseRedirect(reverse('wiki:index'))
            else:
                return HttpResponse(f'There is a record with {title} as the Title')
        else:
            return render(request, 'encyclopedia/add.html', {
                "form": util.AddWikiForm()
            })
    else:
        return render(request, "encyclopedia/add.html", {
            'form': util.AddWikiForm()
        })


def edit(request, title):
    if request.method != "POST":
        form = util.EditWikiForm(initial={'title': title, 'content': util.get_entry(title)})
        return render(request, 'encyclopedia/edit.html', {
            'title': title, 'form': form
        })
    elif request.method == 'POST':
        form = util.EditWikiForm(request.POST)
        if form.is_valid():
            new_title = form.cleaned_data['title']
            new_content = form.cleaned_data['content']
            if form.has_changed():
                if title != new_title:
                    util.delete_entry(title)
                    util.save_entry(new_title, new_content)
                    return HttpResponseRedirect(reverse('wiki:index'))

                else:
                    util.save_entry(new_title, new_content)
                    return HttpResponseRedirect(reverse('wiki:index'))
            else:
                return HttpResponse("The entry has not been altered")
        else:
            return render(request, "encyclopedia/edit", {
                'form': util.EditWikiForm(initial={'title': title, 'content': util.get_entry(title)})
            })


def search(request):
    if request.method == "POST":
        try:
            s_form = util.SearchWikiForm(request.POST)
            s_form.is_valid()
            s_query = s_form.cleaned_data['q']
            s_query = s_query.lower()
            results_in_titles = set()
            for entry in util.list_entries():
                if s_query in entry.lower() or s_query in util.get_entry(entry).lower():
                    results_in_titles.add(entry)
                else:
                    continue
            return render(request, 'encyclopedia/search.html', {
                'results_in_titles': results_in_titles,
                'query': s_query
            })
        except:
            raise Exception


def random(request):
    entries = util.list_entries()
    rand = rn.randint(0, len(entries) - 1)
    return wiki(request, entries[rand])


def wiki(request, title):
    record_not_found = "Sorry, The Entry does not Exist"
    if title in util.list_entries():
        return render(request, "encyclopedia/wiki.html", {
            "title": title, "content": markdown2.markdown(util.get_entry(title))
        })
    else:
        return render(request, 'encyclopedia/error.html', {
            "err_message": record_not_found
        })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Add
{% endblock %}

{% block body %}
<h1>Add Entry</h1>
<form method="post" action="{%url 'wiki:add'%}">
{%csrf_token%}
    {{form}}
    <button type="submit">Add Entry</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit
{% endblock %}

{% block body %}
<h1>Edit {{title}}</h1>

<form method="post" action="{%url 'wiki:edit' title%}">
    {%csrf_token%}
    {{form}}
    <button type="submit">Commit Changes</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}
<h1>Error :{{title}}</h1>

{{err_message}}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for title in entries %}
        <a href="{%url 'wiki:get' title %}"><li>{{ title }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{%url 'wiki:search'%}" method="post">
                    {%csrf_token%}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{%url 'wiki:add'%}"> Create New Page</a>
                </div>
                <div>
                    <a href="{%url 'wiki:random'%}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search Results for {{query}}
{% endblock %}

{% block body %}
<h1> Search match for ...{{query}}...</h1>
<div>
    <div>
    <ul>
    {%for title in results_in_titles%}
    <div><li><a href="{%url 'wiki:get' title%}">{{title}}</a> </li></div>
    {%empty%}}
        <div><p>No Titles with {{query}} in them</p></div>
    {%endfor%}
    </ul>
    </div>
    <div>
        <ul>
            {%for title in results_in_contents%}
            <div><li><a href="{%url 'wiki:get' title%}">{{title}}</a> </li></div>
            {%empty%}
            {%endfor%}
        </ul>
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}

{{content|safe}}
<a href="{%url 'wiki:edit' title%}">Edit This Record</a>
{% endblock %}